env:
  browser: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - "plugin:prettier/recommended"
  - "prettier/@typescript-eslint"
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
  project: tsconfig.json
  tsconfigRootDir: functions
plugins:
  - '@typescript-eslint'
rules: {}
